### ISSUE TITLE
`multilpe` vs. `lazyMultiple`

### ISSUE THREAD

**Issue by leanto** [Roaders/ts-command-line-args#25]
As far as I can tell from searching the code, `multiple` and `lazyMultiple` are treated exactly the same. The documentation for `lazyMultiple` says:

```typescript
    /**
     * Set this flag if the option accepts multiple values. In the output, you will receive an array of values each passed through the `type` function.
     */
    multiple?: boolean;
    /**
     * Identical to `multiple` but with greedy parsing disabled.
     */
    lazyMultiple?: boolean;
```

But after looking through all of the code related to `multiple` and, `lazyMultiple`, they always appear together. I've tried going through the history and commit cff1da3f022a6c729cbfa3a0c20c914c3f37b388 seems to be the most relevant, but it only adds another check. Is `lazyMultiple` just a legacy option now?

**Comment by Roaders** [comment]
These 2 args are just passed through to `command-line-args`. This library does nothing with them and TBH I don't understand what they do!! I have included them just so that whatever you can do with `command-line-args` you can do here.
