### ISSUE TITLE
`optional: true` is required can't use `optional: false`

### ISSUE THREAD

**Issue by aubelscirclein** [Roaders/ts-command-line-args#28]
This works
```
interface IArgs{
    forYear: number;
    forMonth: number;
    awsProfile?: string;
}

export const args = parse<IArgs>({
    forYear: { type: Number, optional: true },
    forMonth: { type: Number, optional: true },
    awsProfile: { type: String, optional: true },
}, {});
```

But this doesn't:
```
interface IArgs{
    forYear: number;
    forMonth: number;
    awsProfile?: string;
}

export const args = parse<IArgs>({
    forYear: { type: Number, optional: false },
    forMonth: Number,
    awsProfile: { type: String, optional: true },
}, {});
```

**Comment by aubelscirclein** [comment]
```
        "ts-command-line-args": "^2.2.1"
        "typescript": "^4.5.4",
```

**Comment by Roaders** [comment]
This is expected. The args object that you have to create is just a run time version of the interface that you define at compile time. It's shape is strictly govorned by the conditional types so it specifies that if it's optional you must have `optional: true` not `optional: boolean`. I could define `optional?: false` on the non optional type but that would further complicate a complicated area.

**Comment by aubelscirclein** [comment]
How would I know this without looking at the typescript defintions?
