### ISSUE TITLE
Can't find write-markdown

### ISSUE THREAD

**Issue by oliverfn** [Roaders/ts-command-line-args#33]
Hey there, 
I know this is a very simple issue and I'm probably just missing something, but I get:

`bash: write-markdown: command not found`, when e.g. using:

```bash
$ write-markdown -m test.md -j lib/types/constants/app.constants.js
```

Ofc I am aware of what that error means  -- my issue rather being, that I do not find any resource where to download the `write-markdown`  tool. 
I am on a windows btw, maybe it is preinstalled on unix systems, I have no idea.

Thanks for your help and best wishes!

**Comment by Roaders** [comment]
you need to install it... You can either install it in your project or you can install it globally:
`npm install -g ts-command-line-args`
