### ISSUE TITLE
Any way to add a default number?

### ISSUE THREAD

**Issue by ohare93** [Roaders/ts-command-line-args#43]
```
interface IArguments {
  latest?: number;
  ...
}

export const args = parse<IArguments>(
  {
    latest: {type: Number, optional: true},
    ...
  }
);
```

I have the above setup. I can pass `--latest 3` to get 3. Is there any way I can have it so that passing `--latest` only will result in 1? I cannot seem to get the typing to be happy with passing a boolean, or defaulting to 1 when `--latest` is passed and null when it is not.

Thanks for any help 👍

**Comment by Roaders** [comment]
no, you can't have a number as a default value for a boolean cli arg.

**Comment by ohare93** [comment]
How about a default for a number cli arg? Or is it always mandatory for a value to be passed?
