### ISSUE TITLE
Using `multiple: true` in combination with `alias`

### ISSUE THREAD

**Issue by dan-covaliu** [Roaders/ts-command-line-args#46]
From the readme file examples, if we use the alias `'e'` for the `excludePaths?: string[]`, then when we run 

`$ node exampleConfig.js --sourcePath source --targetPath target --filter src -e=one -e=two
`
we get an error. Though 
`$ node exampleConfig.js --sourcePath source --targetPath target --filter src -e one two
`
seems to work

**Comment by Roaders** [comment]
This is part of the base package that this package depends on. I assume that an alias can't be specified more than once.
