### ISSUE TITLE
OptionContent is missing "hide" field

### ISSUE THREAD

**Issue by OmgImAlexis** [Roaders/ts-command-line-args#8]
Trying to follow https://github.com/75lb/command-line-usage/wiki/How-to-hide-an-option-in-the-usage-guide

I couldn't find another way to pass this so I'm using this but I get a type error.

```
	optionSections: [{
		hide: ['src']
	}],
```

**Comment by Roaders** [comment]
That code should work now. I added the missing properties to the `OptionContent` section type definition. Thanks for raising the issue.
